### ISSUE TITLE
Errors while running test for fern

### ISSUE THREAD

**Issue by Zvyozdo4ka** [sxyu/svox2#105]
Hello!

I am trying to cope with running test for fern case. But I got these errors.
Does anybody know how to debug it? 
Has anyone successfully run this test?

Many thanks in advance.

```
Traceback (most recent call last):
  File "opt.py", line 389, in <module>
    eval_step()
  File "opt.py", line 324, in eval_step
    rgb_pred_test = grid.volume_render_image(cam, use_kernel=True)
  File "/home/yulduz/anaconda3/envs/plenoxel/lib/python3.8/site-packages/svox2/svox2.py", line 1159, in volume_render_image
    if self.basis_type != BASIS_TYPE_MLP and imrend_fn_name in _C.__dict__ and not torch.is_grad_enabled() and not return_raylen:
AttributeError: 'NoneType' object has no attribute '__dict__'
```

**Comment by sxyu** [comment]
Hi, it appears the CUDA extension failed to install here.
`pip install -e . --verbose` may reveal an error
