### ISSUE TITLE
How much GPU memory is needed for training?

### ISSUE THREAD

**Issue by kxhit** [sxyu/svox2#14]
Hi, thanks for the great work!

I'm curious about how much GPU memory is needed for training the models. I didn't find the relevant explanation in the paper. Thanks!

**Comment by y22ma** [comment]
Curious about this as well. Struggling to train a scene on a 8GB graphics card without running into memory allocation failure. Just wondering what are the knobs we can play with to reduce memory requirements?

**Comment by saunair** [comment]
Was wondering if there if we could work on a multi-gpu mode / split the voxel training into parts. Most of the time the training fails at the upsampling step

**Comment by y22ma** [comment]
> Curious about this as well. Struggling to train a scene on a 8GB graphics card without running into memory allocation failure. Just wondering what are the knobs we can play with to reduce memory requirements?

Finally got my model to train! Turns out the background layers take up alot of memory and shaving that down allowed me to train a model on limited memory.

**Comment by entmike** [comment]
> 



> Turns out the background layers take up alot of memory and shaving that down allowed me to train a model on limited memory.

Can you share where you made the changes?  I get about 5 epochs into training on a 3080 Ti with the sample Truck dataset and then it bombs out with this error:

```
RuntimeError: CUDA out of memory. Tried to allocate 1.55 GiB (GPU 0; 11.75 GiB total capacity; 6.67 GiB already allocated; 1.33 GiB free; 7.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by neurall** [comment]
I was getting out of memory when training lego_real_night_radial and started upsampling to 512 on 3080 with 11g mem. but thx to hint above i noticed there is on top of syn also syn_nv in config dir with bunch of different constants seems like low mem config . i provided --config configs/syn_nv.json and didnt crashed.training done used memory was in that dataset around 7.7g

**Comment by hailangWu-Aval** [comment]
Is that anyone in this project can give some suggestions for the question ?

**Comment by pjmsullivan** [comment]
I am also having out of memory errors, although, I am using a mobile GPU with only 4 GB of capacity for CUDA.  By reducing the settings in the config file (as mentioned by @neurall, @entmike, and @y22ma above), I was able to run Plenoxels, although the settings were so low, the output is unusable.

**Comment by neurall** [comment]
Hi guys.
At least for Cool Tank dataset minimum gpu mem for default 10 epochs as in config seems to be 32g ram and 16g gpu which are typically found only in cloud. So my 3080 is sitting idle. But I wanted to play with this so baad.... Plus given how hard it is to get hands on any gpu nowadays. I created colab

BEWARE for now. it will not work on Free colab. Reason being

As mentioned. svox2 currently needs 32g ram to train M60 Tank dataset and 16G gpu where it even then just barely fits
free colab has just 12g ram and 15g gpu.

https://colab.research.google.com/drive/1SODy_HiP_kkjL5E4IiBM1XZsD1HofElZ

I set colab as editable for anyone to make it better. so please be carefull to keep it working if you do changes.
I someone finds a way to tweak it to fit free colab and still have acceptably good output quality that would be great service to community.

Enjoy. 
Ladislav
Sadly
Due

**Comment by Coscatter** [comment]
> > Curious about this as well. Struggling to train a scene on a 8GB graphics card without running into memory allocation failure. Just wondering what are the knobs we can play with to reduce memory requirements?
> 
> Finally got my model to train! Turns out the background layers take up alot of memory and shaving that down allowed me to train a model on limited memory.

I wonder which version of Driver & cuda did you use. I use GTX2060s ,driver 465, cuda 11.3, but i cant pip install .  right  follow the instruction.

**Comment by Miles629** [comment]
It seems that 15.78 GiB can't satisfy the memory needed.
```
Traceback (most recent call last):
  File "opt.py", line 605, in <module>
    train_step()
  File "opt.py", line 595, in train_step
    grid.optim_sh_step(lr_sh, beta=args.rms_beta, optim=args.sh_optim)
  File "/home/macaoyuan/.local/lib/python3.8/site-packages/svox2/svox2.py", line 2024, in optim_sh_step
    self.sh_rms = torch.zeros_like(self.sh_data.data) # FIXME init?
RuntimeError: CUDA out of memory. Tried to allocate 1.53 GiB (GPU 0; 15.78 GiB total capacity; 10.66 GiB already allocated; 1.13 GiB free; 13.49 GiB reserved in total by PyTorch)

```
And when I set <GPU_id> "0,1" here (try to use 2 gpus) :
`./launch.sh <exp_name> <GPU_id> <data_dir> -c <config>`
It seems that only one gpu was used.
```
Traceback (most recent call last):
  File "opt.py", line 605, in <module>
    train_step()
  File "opt.py", line 595, in train_step
    grid.optim_sh_step(lr_sh, beta=args.rms_beta, optim=args.sh_optim)
  File "/home/macaoyuan/.local/lib/python3.8/site-packages/svox2/svox2.py", line 2024, in optim_sh_step
    self.sh_rms = torch.zeros_like(self.sh_data.data) # FIXME init?
RuntimeError: CUDA out of memory. Tried to allocate 1.55 GiB (GPU 0; 15.78 GiB total capacity; 10.69 GiB already allocated; 1.12 GiB free; 13.50 GiB reserved in total by PyTorch)

```
I want to know what is the correct way to use two gpu in this work. Is the reason for this phenomenon  that `device = "cuda" if torch.cuda.is_available() else "cpu"`?

**Comment by neurall** [comment]
meantime better alternative pupped up. nvidia just released alternative that trains in seconds instead of minutes and runs on pretty much any gpu https://github.com/NVlabs/instant-ngp
