### ISSUE TITLE
Error during Voxel Optimization: ‘NoneType’ object has no attribute ‘__dict__’

### ISSUE THREAD

**Issue by GaiZhenbiao** [sxyu/svox2#44]
Your work is amazing!!! But I’m having some truble to reproduce the result.
I installed `svox2` using `pip install .` as said in the ReadMe.

```
(plenoxel) nerf2themoon@pop-os:~/plenoxel/svox2$ pip install .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing /home/nerf2themoon/plenoxel/svox2
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Building wheels for collected packages: svox2
  Building wheel for svox2 (setup.py) ... done
  Created wheel for svox2: filename=svox2-0.0.1.dev0+sphtexcub.lincolor.fast-cp38-cp38-linux_x86_64.whl size=3452740 sha256=afa3baeab9cee4640d23f94966a0de8aff7fd5a96b306974b6cdbbea4edae146
  Stored in directory: /tmp/pip-ephem-wheel-cache-eoqumo0a/wheels/57/94/9f/8f7f818790c817e36f6a19ba5a5ee388feb9f3ff8b5cb880a9
Successfully built svox2
Installing collected packages: svox2
  Attempting uninstall: svox2
    Found existing installation: svox2 0.0.1.dev0+sphtexcub.lincolor.fast
    Uninstalling svox2-0.0.1.dev0+sphtexcub.lincolor.fast:
      Successfully uninstalled svox2-0.0.1.dev0+sphtexcub.lincolor.fast
Successfully installed svox2-0.0.1.dev0+sphtexcub.lincolor.fast
```
but it crashed when excuting lauch.sh, emitting logs below: 
```
Launching experiment fern
GPU 0
EXTRA /home/nerf2themoon/plenoxel/svox2/data/nerf_llff_data/fern -c configs/llff.json
CKPT ckpt/fern
LOGFILE ckpt/fern/log
/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/svox2/utils.py:39: UserWarning: CUDA extension svox2.csrc could not be loaded! Operations will be slow.
Please do not import svox in the svox2 source directory.
  warn("CUDA extension svox2.csrc could not be loaded! " +
Detected LLFF dataset
Using pre-scaled images from /home/nerf2themoon/plenoxel/svox2/data/nerf_llff_data/fern/images_4
Loaded LLFF data /home/nerf2themoon/plenoxel/svox2/data/nerf_llff_data/fern 16.985296178676084 80.00209740336334
recentered (3, 4)
[1.3765233 5.48648  ]
Overriding offset 250-> 250
dmin = 1.376523, dmax = 5.486480, invz = 0, offset = 250
100%|█████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 26.84it/s]
z_bounds from LLFF: [1.3765232563018799, 5.486480236053467] (not used)
scene_radius [1.496031746031746, 1.6613756613756614, 1.0]
 Generating rays, scaling factor 1
/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180588308/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Detected LLFF dataset
Using pre-scaled images from /home/nerf2themoon/plenoxel/svox2/data/nerf_llff_data/fern/images_4
Loaded LLFF data /home/nerf2themoon/plenoxel/svox2/data/nerf_llff_data/fern 16.985296178676084 80.00209740336334
recentered (3, 4)
[1.3765233 5.48648  ]
Overriding offset 250-> 250
dmin = 1.376523, dmax = 5.486480, invz = 0, offset = 250
100%|███████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 28.04it/s]
100%|███████████████████████████████████████████████████| 120/120 [00:00<00:00, 153309.92it/s]
z_bounds from LLFF: [1.3765232563018799, 5.486480236053467] (not used)
scene_radius [1.496031746031746, 1.6613756613756614, 1.0]
Morton code requires a cube grid of power-of-2 size, ignoring...
Render options RenderOptions(backend='cuvol', background_brightness=0.5, step_size=0.5, sigma_thresh=1e-08, stop_thresh=1e-07, last_sample_opaque=False, near_clip=0.0, use_spheric_clip=False, random_sigma_std=0.0, random_sigma_std_background=0.0)
 Selecting random rays
Eval step
  0%|                                                                   | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "opt.py", line 471, in <module>
    eval_step()
  File "opt.py", line 406, in eval_step
    rgb_pred_test = grid.volume_render_image(cam, use_kernel=True)
  File "/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/svox2/svox2.py", line 1159, in volume_render_image
    if self.basis_type != BASIS_TYPE_MLP and imrend_fn_name in _C.__dict__ and not torch.is_grad_enabled() and not return_raylen:
AttributeError: 'NoneType' object has no attribute '__dict__'
DETACH
```

Also, I tried install it using setup.py, here’s the output: 
```
setup.py:25: UserWarning: The environment variable `CUB_HOME` was not found.Installation will fail if your system CUDA toolkit version is less than 11.NVIDIA CUB can be downloaded from `https://github.com/NVIDIA/cub/releases`. You can unpack it to a location of your choice and set the environment variable `CUB_HOME` to the folder containing the `CMakeListst.txt` file.
  warnings.warn(
running install
running bdist_egg
running egg_info
creating svox2.egg-info
writing svox2.egg-info/PKG-INFO
writing dependency_links to svox2.egg-info/dependency_links.txt
writing top-level names to svox2.egg-info/top_level.txt
writing manifest file 'svox2.egg-info/SOURCES.txt'
package init file 'svox2/csrc/__init__.py' not found (or not a regular file)
reading manifest file 'svox2.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'svox2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/svox2
copying svox2/svox2.py -> build/lib.linux-x86_64-3.8/svox2
copying svox2/__init__.py -> build/lib.linux-x86_64-3.8/svox2
copying svox2/version.py -> build/lib.linux-x86_64-3.8/svox2
copying svox2/utils.py -> build/lib.linux-x86_64-3.8/svox2
copying svox2/defs.py -> build/lib.linux-x86_64-3.8/svox2
running build_ext
building 'svox2.csrc' extension
creating /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8
creating /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2
creating /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc
Emitting ninja build file /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Using envvar MAX_JOBS (4) as the number of workers...
[1/8] c++ -MMD -MF /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/svox2.o.d -pthread -B /home/nerf2themoon/anaconda3/envs/plenoxel/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/TH -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/THC -I/home/nerf2themoon/anaconda3/envs/plenoxel/include/python3.8 -c -c /home/nerf2themoon/plenoxel/svox2/svox2/csrc/svox2.cpp -o /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/svox2.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=csrc -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
[2/8] /usr/bin/nvcc  -I/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/TH -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/THC -I/home/nerf2themoon/anaconda3/envs/plenoxel/include/python3.8 -c -c /home/nerf2themoon/plenoxel/svox2/svox2/csrc/render_lerp_kernel_cuvol.cu -o /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/render_lerp_kernel_cuvol.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=csrc -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include/render_util.cuh(582): warning: parameter "ray_id" was declared but never referenced

/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include/render_util.cuh(633): warning: parameter "opt" was declared but never referenced

/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include/render_util.cuh(634): warning: parameter "ray_id" was declared but never referenced

[3/8] /usr/bin/nvcc  -I/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/TH -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/THC -I/home/nerf2themoon/anaconda3/envs/plenoxel/include/python3.8 -c -c /home/nerf2themoon/plenoxel/svox2/svox2/csrc/misc_kernel.cu -o /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/misc_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=csrc -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include/render_util.cuh(582): warning: parameter "ray_id" was declared but never referenced

/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include/render_util.cuh(633): warning: parameter "opt" was declared but never referenced

/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include/render_util.cuh(634): warning: parameter "ray_id" was declared but never referenced

/home/nerf2themoon/plenoxel/svox2/svox2/csrc/misc_kernel.cu(57): warning: function "<unnamed>::device::accel_linf_dist_transform_kernel" was declared but never referenced

[4/8] /usr/bin/nvcc  -I/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/TH -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/THC -I/home/nerf2themoon/anaconda3/envs/plenoxel/include/python3.8 -c -c /home/nerf2themoon/plenoxel/svox2/svox2/csrc/svox2_kernel.cu -o /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/svox2_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=csrc -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
[5/8] /usr/bin/nvcc  -I/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/TH -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/THC -I/home/nerf2themoon/anaconda3/envs/plenoxel/include/python3.8 -c -c /home/nerf2themoon/plenoxel/svox2/svox2/csrc/render_lerp_kernel_nvol.cu -o /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/render_lerp_kernel_nvol.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=csrc -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include/render_util.cuh(582): warning: parameter "ray_id" was declared but never referenced

/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include/render_util.cuh(633): warning: parameter "opt" was declared but never referenced

/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include/render_util.cuh(634): warning: parameter "ray_id" was declared but never referenced

/home/nerf2themoon/plenoxel/svox2/svox2/csrc/render_lerp_kernel_nvol.cu(112): warning: parameter "color_cache" was declared but never referenced

[6/8] /usr/bin/nvcc  -I/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/TH -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/THC -I/home/nerf2themoon/anaconda3/envs/plenoxel/include/python3.8 -c -c /home/nerf2themoon/plenoxel/svox2/svox2/csrc/render_svox1_kernel.cu -o /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/render_svox1_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=csrc -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include/render_util.cuh(582): warning: parameter "ray_id" was declared but never referenced

/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include/render_util.cuh(633): warning: parameter "opt" was declared but never referenced

/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include/render_util.cuh(634): warning: parameter "ray_id" was declared but never referenced

[7/8] /usr/bin/nvcc  -I/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/TH -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/THC -I/home/nerf2themoon/anaconda3/envs/plenoxel/include/python3.8 -c -c /home/nerf2themoon/plenoxel/svox2/svox2/csrc/loss_kernel.cu -o /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/loss_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=csrc -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include/render_util.cuh(582): warning: parameter "ray_id" was declared but never referenced

/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include/render_util.cuh(633): warning: parameter "opt" was declared but never referenced

/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include/render_util.cuh(634): warning: parameter "ray_id" was declared but never referenced

/home/nerf2themoon/plenoxel/svox2/svox2/csrc/loss_kernel.cu(23): warning: parameter "ndc_coeffx" was declared but never referenced

/home/nerf2themoon/plenoxel/svox2/svox2/csrc/loss_kernel.cu(24): warning: parameter "ndc_coeffy" was declared but never referenced

/home/nerf2themoon/plenoxel/svox2/svox2/csrc/loss_kernel.cu(25): warning: parameter "z" was declared but never referenced

[8/8] /usr/bin/nvcc  -I/home/nerf2themoon/plenoxel/svox2/svox2/csrc/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/TH -I/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/THC -I/home/nerf2themoon/anaconda3/envs/plenoxel/include/python3.8 -c -c /home/nerf2themoon/plenoxel/svox2/svox2/csrc/optim_kernel.cu -o /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/optim_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=csrc -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
g++ -pthread -shared -B /home/nerf2themoon/anaconda3/envs/plenoxel/compiler_compat -L/home/nerf2themoon/anaconda3/envs/plenoxel/lib -Wl,-rpath=/home/nerf2themoon/anaconda3/envs/plenoxel/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/svox2.o /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/svox2_kernel.o /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/render_lerp_kernel_cuvol.o /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/render_lerp_kernel_nvol.o /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/render_svox1_kernel.o /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/misc_kernel.o /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/loss_kernel.o /home/nerf2themoon/plenoxel/svox2/build/temp.linux-x86_64-3.8/svox2/csrc/optim_kernel.o -L/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/lib -L/usr/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-3.8/svox2/csrc.cpython-38-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/svox2
copying build/lib.linux-x86_64-3.8/svox2/svox2.py -> build/bdist.linux-x86_64/egg/svox2
copying build/lib.linux-x86_64-3.8/svox2/__init__.py -> build/bdist.linux-x86_64/egg/svox2
copying build/lib.linux-x86_64-3.8/svox2/version.py -> build/bdist.linux-x86_64/egg/svox2
copying build/lib.linux-x86_64-3.8/svox2/csrc.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/svox2
copying build/lib.linux-x86_64-3.8/svox2/utils.py -> build/bdist.linux-x86_64/egg/svox2
copying build/lib.linux-x86_64-3.8/svox2/defs.py -> build/bdist.linux-x86_64/egg/svox2
byte-compiling build/bdist.linux-x86_64/egg/svox2/svox2.py to svox2.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/svox2/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/svox2/version.py to version.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/svox2/utils.py to utils.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/svox2/defs.py to defs.cpython-38.pyc
creating stub loader for svox2/csrc.cpython-38-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/svox2/csrc.py to csrc.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying svox2.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying svox2.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying svox2.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying svox2.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying svox2.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/svox2-0.0.1.dev0+sphtexcub.lincolor.fast-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing svox2-0.0.1.dev0+sphtexcub.lincolor.fast-py3.8-linux-x86_64.egg
removing '/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/svox2-0.0.1.dev0+sphtexcub.lincolor.fast-py3.8-linux-x86_64.egg' (and everything under it)
creating /home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/svox2-0.0.1.dev0+sphtexcub.lincolor.fast-py3.8-linux-x86_64.egg
Extracting svox2-0.0.1.dev0+sphtexcub.lincolor.fast-py3.8-linux-x86_64.egg to /home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages
svox2 0.0.1.dev0+sphtexcub.lincolor.fast is already the active version in easy-install.pth

Installed /home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/svox2-0.0.1.dev0+sphtexcub.lincolor.fast-py3.8-linux-x86_64.egg
Processing dependencies for svox2==0.0.1.dev0+sphtexcub.lincolor.fast
Finished processing dependencies for svox2==0.0.1.dev0+sphtexcub.lincolor.fast
```

I tried to install `jaxlib` as mentioned is other issues, install the latest CUDA toolkit and cuDNN, as well as install ninja, but none of them solved my problem.
I also checked `svox2.py`, it seems that svox2 could not load C extentions correctly, since the ‘csrc.cpython-38-x86_64-linux-gnu.so’ emitted an exception when I tried to import it:

```
In [2]: import svox2.csrc
/home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/svox2/utils.py:39: UserWarning: CUDA extension svox2.csrc could not be loaded! Operations will be slow.
Please do not import svox in the svox2 source directory.
  warn("CUDA extension svox2.csrc could not be loaded! " +
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [2], in <module>
----> 1 import svox2.csrc

ImportError: /home/nerf2themoon/anaconda3/envs/plenoxel/lib/python3.8/site-packages/svox2/csrc.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv
```

I’m using a Nvidia RTX 3080Ti on pop_os 21.10, cuda version 11.3. Is anybody kind enough to point out how to solve this problem? Thanks in advance!

**Comment by UestcJay** [comment]
hi, do you solve the problem?

**Comment by youyoubud** [comment]
I have the same question. Has anyone solved this problem?

**Comment by UestcJay** [comment]
> 

after you install svox2, just simply remove the svox2 folder.

**Comment by tomerjr** [comment]
> 

can you explain what do you mean exactly? what is the svox2 folder? the entire project? what do you mean by "installed svox2"?
