### ISSUE TITLE
AssertionError: CUDA extension is currently required for accelerate

### ISSUE THREAD

**Issue by puallee** [sxyu/svox2#49]
I still have the probelm of AssertionError: CUDA extension is currently required for accelerate
ubuntu@ubuntu-broncus:/erick/rendering/svox2-master/svox2-master/opt$ python3.8 render_imgs.py /home/raid/erickData/data/TanksAndTempleBG/Train/
../svox2/utils.py:39: UserWarning: CUDA extension svox2.csrc could not be loaded! Operations will be slow.
Please do not import svox in the svox2 source directory.
warn("CUDA extension svox2.csrc could not be loaded! " +
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Loading model from: /home/ubuntu/.local/lib/python3.8/site-packages/lpips/weights/v0.1/vgg.pth
Defaulting to extended NSVF dataset
LOAD NSVF DATA /home/raid/erickData/data/TanksAndTempleBG/Train/ split test
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 58.04it/s]
NORMALIZE BY? camera
scene_scale 2.0069090349061196
intrinsics (loaded reso) Intrin(fx=580.62451171875, fy=580.62451171875, cx=490.75, cy=273.0)
Traceback (most recent call last):
File "render_imgs.py", line 116, in
grid = svox2.SparseGrid.load(args.ckpt, device=device)
File "../svox2/svox2.py", line 1629, in load
grid.accelerate()
File "../svox2/svox2.py", line 1491, in accelerate
assert (
AssertionError: CUDA extension is currently required for accelerate
Can some help me ，my environment is python3.8 torch 1.8.0+cu111 nvidia driver 460.91.03 gpu 3090 ，torchaudio 0.8.0 torchvision 0.9.0+cu111
and gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu118.04)

**Comment by parilo** [comment]
I have the same issue, tried to install csrc library with cmake and got
```
(plenoxel) anton@anton-cuda:~/devel/slam/plenoxels/svox2/svox2/build$ cmake -DCMAKE_PREFIX_PATH=~/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch ../csrc/
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CUDA compiler identification is NVIDIA 11.4.48
-- Check for working CUDA compiler: /home/anton/anaconda3/envs/plenoxel/bin/nvcc
-- Check for working CUDA compiler: /home/anton/anaconda3/envs/plenoxel/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- CUDA enabled
-- Found PythonInterp: /home/anton/anaconda3/envs/plenoxel/bin/python (found version "3.8.8") 
-- Found PythonLibs: /home/anton/anaconda3/envs/plenoxel/lib/libpython3.8.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found pybind11: /home/anton/anaconda3/envs/plenoxel/include (found version "2.7.1" )
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /home/anton/anaconda3/envs/plenoxel (found version "11.4") 
-- Caffe2: CUDA detected: 11.4
-- Caffe2: CUDA nvcc is: /home/anton/anaconda3/envs/plenoxel/bin/nvcc
-- Caffe2: CUDA toolkit directory: /home/anton/anaconda3/envs/plenoxel
-- Caffe2: Header version is: 11.4
-- Found CUDNN: /home/anton/anaconda3/envs/plenoxel/lib/libcudnn.so  
-- Found cuDNN: v8.2.1  (include: /home/anton/anaconda3/envs/plenoxel/include, library: /home/anton/anaconda3/envs/plenoxel/lib/libcudnn.so)
-- /home/anton/anaconda3/envs/plenoxel/lib/libnvrtc.so shorthash is 9d774d23
-- Autodetected CUDA architecture(s):  7.5 6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_61,code=sm_61
CMake Warning at /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:66 (find_package)


-- Found Torch: /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/lib/libtorch.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/anton/devel/slam/plenoxels/svox2/svox2/build
(plenoxel) anton@anton-cuda:~/devel/slam/plenoxels/svox2/svox2/build$ make -j 1
Scanning dependencies of target svox2-test
[ 11%] Building CUDA object CMakeFiles/svox2-test.dir/loss_kernel.cu.o
In file included from /home/anton/anaconda3/envs/plenoxel/bin/..//include/thrust/system/cuda/detail/execution_policy.h:33,
                 from /home/anton/anaconda3/envs/plenoxel/bin/..//include/thrust/iterator/detail/device_system_tag.h:23,
                 from /home/anton/anaconda3/envs/plenoxel/bin/..//include/thrust/iterator/iterator_traits.h:111,
                 from /home/anton/anaconda3/envs/plenoxel/bin/..//include/thrust/detail/type_traits/pointer_traits.h:23,
                 from /home/anton/anaconda3/envs/plenoxel/bin/..//include/thrust/type_traits/is_contiguous_iterator.h:27,
                 from /home/anton/anaconda3/envs/plenoxel/bin/..//include/thrust/type_traits/is_trivially_relocatable.h:19,
                 from /home/anton/anaconda3/envs/plenoxel/bin/..//include/thrust/detail/complex/complex.inl:20,
                 from /home/anton/anaconda3/envs/plenoxel/bin/..//include/thrust/complex.h:1031,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/c10/util/complex.h:8,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/c10/util/Half.h:14,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/c10/core/ScalarType.h:5,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/c10/core/Scalar.h:11,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/ATen/Operators.h:13,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:3,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/ATen/Context.h:4,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/ATen/ATen.h:9,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/anton/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/torch/extension.h:4,
                 from /home/anton/devel/slam/plenoxels/svox2/svox2/csrc/loss_kernel.cu:4:
/home/anton/anaconda3/envs/plenoxel/bin/..//include/thrust/system/cuda/config.h:76:10: fatal error: cub/util_namespace.cuh: No such file or directory
   76 | #include <cub/util_namespace.cuh> // This includes <cub/version.cuh> in newer releases.
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/svox2-test.dir/build.make:63: CMakeFiles/svox2-test.dir/loss_kernel.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/svox2-test.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
(plenoxel) anton@anton-cuda:~/devel/slam/plenoxels/svox2/svox2/build$ 
```

**Comment by parilo** [comment]
I faced this issue, so basically pip install haven't compile CUDA extension without any warning. Te see what you need to compile do
```
cd svox2
cmake csrc
make -j 1
```
When you make sure it compiles just reinstall svox2 with pip, this time it should compile the extension.
```
pip uninstall svox2
pip install .
```

**Comment by LitterWindwind** [comment]
When I use terminal to run, it's ok. But when I use pycharm to debug the code, I meet the same error. I have tried on three different machine, which is strange.

**Comment by parilo** [comment]
> ```
> 
> ```
> 
> 
>     
> 
>   
> 
> how can I solve the question ?

I didn't have this issue. It seems that either csrc.cpython-38-x86_64-linux-gnu.so wasn't linked with some library properly or this library doesn't load when you import csrc. Please read carefully messages during csrc compilation. When you do cmake and make. Maybe you spot something.

**Comment by yangqingqing007** [comment]
I meet the same problem~

**Comment by laulampaul** [comment]
> I meet the same problem~

I solve the issue by using docker. I hope it can help you.

**Comment by Utopiah** [comment]
Hi @laulampaul, can you please share your Dockerfile?

**Comment by muxizju** [comment]
Reason: the compiled package name and the folder name in the project are both "svox2", they will be mis-imported when using in the opt.py script.
Solution: aftering "pip install .", just simply remove the folder"./svox2/svox2". Then everything will work
