### ISSUE TITLE
"./launch.sh <exp_name> <GPU_id> <data_dir> -c <config>"  how can i run this command concretely?

### ISSUE THREAD

**Issue by lideng4523** [sxyu/svox2#62]

**Comment by Visuals3D** [comment]
You go into the "opt" folder and run the command replacing <exp_name> with some name you want the training results bo be saved by <gpu_id> is for most of us with a single gpu a 0 and <data_dir> must be a path from the "opt" folder to where you saved the downloaded example folder of the lego scene or another scene. 
<config> has to be replaced with a path to the config matching the type of scene you want to train. If its a synthetic dataset use configs/syn.json. 

After you started the command training will start. But the command will exit in the console. To follow the informations live use this command: tail -f ckpt/<exp_name>/log
It will print everything to console. 

I hope this helps. To get informations about other args that can be added to the command you can take a look in this file: https://github.com/sxyu/svox2/blob/master/opt/opt.py

Hope that helps.

**Comment by Visuals3D** [comment]
Errors will also be printed into ckpt/<exp_name>/log. So maby you already run the command correctly but it throws errors in the background.

**Comment by lideng4523** [comment]
> You go into the "opt" folder and run the command replacing <exp_name> with some name you want the training results bo be saved by. <gpu_id> is for most of us with a single gpu a 0 and <data_dir> must be a path from the "opt" folder to where you saved the downloaded example folder of the lego scene or another scene. has to be replaced with a path to the config file matching the type of scene you want to train. If it is a synthetic dataset use configs/syn.json.
> 
> After you run the command training will start. But the command will exit in the console. To follow the informations live use this command: tail -f ckpt/<exp_name>/log It will print everything to console.
> 
> I hope this helps. To get informations about other args that can be added to the command you can take a look in this file: https://github.com/sxyu/svox2/blob/master/opt/opt.py
> 
> Hope that helps.


> You go into the "opt" folder and run the command replacing <exp_name> with some name you want the training results bo be saved by. <gpu_id> is for most of us with a single gpu a 0 and <data_dir> must be a path from the "opt" folder to where you saved the downloaded example folder of the lego scene or another scene. has to be replaced with a path to the config file matching the type of scene you want to train. If it is a synthetic dataset use configs/syn.json.
> 
> After you run the command training will start. But the command will exit in the console. To follow the informations live use this command: tail -f ckpt/<exp_name>/log It will print everything to console.
> 
> I hope this helps. To get informations about other args that can be added to the command you can take a look in this file: https://github.com/sxyu/svox2/blob/master/opt/opt.py
> 
> Hope that helps.

It's very kind of you, think you for helping me. In fact, my head was in whilr because this trouble. I will refer you advice to copy this, and hope we can interact afterwards.

**Comment by UestcJay** [comment]
hi, did you solve the problem?

**Comment by pccross** [comment]
> I ran this instruction "python .\opt.py .\nerf_synthetic\ship\ -t ckpt/res", but there is a error "if self.basis_type != BASIS_TYPE_MLP and imrend_fn_name in _C.**dict** and not torch.is_grad_enabled() and not return_raylen: AttributeError: 'NoneType' object has no attribute '**dict**' ", can you tell me how to do then? Thanks in advance.

I'm getting this exact same error when running the launch.sh.  ****AttributeError: 'NoneType' object has no attribute '__dict__'****  

Here's additional info from log trace, pointing to line 1159 of svox2.py

 Selecting random rays
Eval step
^M  0%|          | 0/6 [00:00<?, ?it/s]^M  0%|          | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "opt.py", line 471, in <module>
    eval_step()
  File "opt.py", line 406, in eval_step
    rgb_pred_test = grid.volume_render_image(cam, use_kernel=True)
  File "/home/pccross38/miniconda3/envs/plenoxel/lib/python3.8/site-packages/svox2/svox2.py", line 1159, in volume_render_image
    if self.basis_type != BASIS_TYPE_MLP and imrend_fn_name in _C.__dict__ and not torch.is_grad_enabled() and not return_raylen:
AttributeError: 'NoneType' object has no attribute '__dict__'

Any thoughts why _dict_ might be empty?
