### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dict' when running launch.sh

### ISSUE THREAD

**Issue by pccross** [sxyu/svox2#81]
Saw someone reported this issue in another thread, but got no response, so opening new issue:
Their error:
I ran this instruction "python .\opt.py .\nerf_synthetic\ship\ -t ckpt/res", but there is a error "if self.basis_type != BASIS_TYPE_MLP and imrend_fn_name in _C.dict and not torch.is_grad_enabled() and not return_raylen: AttributeError: 'NoneType' object has no attribute 'dict' ", can you tell me how to do then? Thanks in advance.

I'm getting this exact same error when running the launch.sh. AttributeError: 'NoneType' object has no attribute 'dict'

Here's additional info from log trace, pointing to line 1159 of svox2.py

Selecting random rays
Eval step
^M 0%| | 0/6 [00:00<?, ?it/s]^M 0%| | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
File "opt.py", line 471, in
eval_step()
File "opt.py", line 406, in eval_step
rgb_pred_test = grid.volume_render_image(cam, use_kernel=True)
File "/home/pccross38/miniconda3/envs/plenoxel/lib/python3.8/site-packages/svox2/svox2.py", line 1159, in volume_render_image
if self.basis_type != BASIS_TYPE_MLP and imrend_fn_name in _C.dict and not torch.is_grad_enabled() and not return_raylen:
AttributeError: 'NoneType' object has no attribute 'dict'

Any thoughts why dict might be empty?

**Comment by WeiLi-THU** [comment]
@pccross I have the same issue, do you now have this fixed?
