### ISSUE TITLE
RuntimeError: t == DeviceType::CUDA INTERNAL ASSERT FAILED after running launch.sh

### ISSUE THREAD

**Issue by basit-7** [sxyu/svox2#82]
I am trying to train on a custom dataset. This is the error that I get. I have tried and searched for possible solutions, but still no luck. 

/home/vispro/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352465323/work/aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Defaulting to extended NSVF dataset
LOAD NSVF DATA /media/vispro/New_Volume/Basit/dtu_scan9_rect_0/data_dir split test
100%|██████████| 4/4 [00:00<00:00, 121.61it/s]
NORMALIZE BY? camera
scene_scale 7.697307158737931
 intrinsics (loaded reso) Intrin(fx=194.02891895575638, fy=194.02891895575638, cx=320.0, cy=256.0)
Render options RenderOptions(backend='cuvol', background_brightness=0.5, step_size=0.5, sigma_thresh=1e-08, stop_thresh=1e-07, last_sample_opaque=False, near_clip=0.35, use_spheric_clip=False, random_sigma_std=0.0, random_sigma_std_background=0.0)
 Selecting random rays
Eval step
  0%|          | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "opt.py", line 471, in <module>
    eval_step()
  File "opt.py", line 406, in eval_step
    rgb_pred_test = grid.volume_render_image(cam, use_kernel=True)
  File "/home/vispro/anaconda3/envs/plenoxel/lib/python3.8/site-packages/svox2/svox2.py", line 1162, in volume_render_image
    return cu_fn(
**RuntimeError: t == DeviceType::CUDA INTERNAL ASSERT FAILED at "/home/vispro/anaconda3/envs/plenoxel/lib/python3.8/site-packages/torch/include/c10/cuda/impl/CUDAGuardImpl.h":24, please report a bug to PyTorch.**

**Comment by synsin0** [comment]
Same problem, fast image rendering is not possible with cuda error.

**Comment by synsin0** [comment]
Have you solved the problem?

**Comment by Visuals3D** [comment]
Same here. Did someone solve this issue?
